<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocationReportsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('location_reports')->insert([
            ['location_report_id' => '1', 'location_id' => '1', 'aggregate_date' => '2019-03-11 00:00:00', 'gmb_account_id' => '002', 'gmb_location_id' => '001',  'gmb_location_name' => '焼肉一番かるび 座光寺店　　', 'gmb_queries_direct' => '222', 'gmb_queries_indirect' => '399', 'gmb_queries_chain' => '66', 'gmb_actions_website' => '50', 'gmb_actions_phone' => '20', 'gmb_actions_driving_directions' => '31', ],
            ['location_report_id' => '2', 'location_id' => '2', 'aggregate_date' => '2019-03-12 00:00:00', 'gmb_account_id' => '002', 'gmb_location_id' => '002',  'gmb_location_name' => '焼肉一番かるび 白根店　　　', 'gmb_queries_direct' => '111', 'gmb_queries_indirect' => '188', 'gmb_queries_chain' => '77', 'gmb_actions_website' => '28', 'gmb_actions_phone' => '40', 'gmb_actions_driving_directions' => '20', ],
            ['location_report_id' => '3', 'location_id' => '3', 'aggregate_date' => '2020-04-12 00:00:00', 'gmb_account_id' => '002', 'gmb_location_id' => '003',  'gmb_location_name' => '焼肉一番かるび 北習志野店　', 'gmb_queries_direct' => '444', 'gmb_queries_indirect' => '322', 'gmb_queries_chain' => '100', 'gmb_actions_website' => '33', 'gmb_actions_phone' => '66', 'gmb_actions_driving_directions' => '0', ],
            ['location_report_id' => '4', 'location_id' => '1', 'aggregate_date' => '2020-04-13 00:00:00', 'gmb_account_id' => '002', 'gmb_location_id' => '001',  'gmb_location_name' => '焼肉一番かるび 座光寺店　　', 'gmb_queries_direct' => '200', 'gmb_queries_indirect' => '232', 'gmb_queries_chain' => '99', 'gmb_actions_website' => '22', 'gmb_actions_phone' => '33', 'gmb_actions_driving_directions' => '22', ],
            ['location_report_id' => '5', 'location_id' => '2', 'aggregate_date' => '2020-05-01 00:00:00', 'gmb_account_id' => '002', 'gmb_location_id' => '002',  'gmb_location_name' => '焼肉一番かるび 白根店　　　', 'gmb_queries_direct' => '144', 'gmb_queries_indirect' => '333', 'gmb_queries_chain' => '33', 'gmb_actions_website' => '30', 'gmb_actions_phone' => '20', 'gmb_actions_driving_directions' => '50', ],
            ['location_report_id' => '6', 'location_id' => '3', 'aggregate_date' => '2020-05-13 00:00:00', 'gmb_account_id' => '002', 'gmb_location_id' => '003',  'gmb_location_name' => '焼肉一番かるび 北習志野店　', 'gmb_queries_direct' => '555', 'gmb_queries_indirect' => '333', 'gmb_queries_chain' => '111', 'gmb_actions_website' => '100', 'gmb_actions_phone' => '133', 'gmb_actions_driving_directions' => '100', ],
            ['location_report_id' => '7', 'location_id' => '1', 'aggregate_date' => '2020-06-10 00:00:00', 'gmb_account_id' => '002', 'gmb_location_id' => '001',  'gmb_location_name' => '焼肉一番かるび 座光寺店　　', 'gmb_queries_direct' => '222', 'gmb_queries_indirect' => '399', 'gmb_queries_chain' => '66', 'gmb_actions_website' => '50', 'gmb_actions_phone' => '20', 'gmb_actions_driving_directions' => '31', ],
            ['location_report_id' => '8', 'location_id' => '2', 'aggregate_date' => '2020-06-14 00:00:00', 'gmb_account_id' => '002', 'gmb_location_id' => '002',  'gmb_location_name' => '焼肉一番かるび 白根店　　　', 'gmb_queries_direct' => '111', 'gmb_queries_indirect' => '188', 'gmb_queries_chain' => '77', 'gmb_actions_website' => '28', 'gmb_actions_phone' => '40', 'gmb_actions_driving_directions' => '20', ],
            ['location_report_id' => '9', 'location_id' => '3', 'aggregate_date' => '2020-07-14 00:00:00', 'gmb_account_id' => '002', 'gmb_location_id' => '003',  'gmb_location_name' => '焼肉一番かるび 北習志野店　', 'gmb_queries_direct' => '444', 'gmb_queries_indirect' => '322', 'gmb_queries_chain' => '100', 'gmb_actions_website' => '33', 'gmb_actions_phone' => '66', 'gmb_actions_driving_directions' => '0', ],
            ['location_report_id' => '10', 'location_id' => '1', 'aggregate_date' => '2020-07-15 00:00:00', 'gmb_account_id' => '002', 'gmb_location_id' => '001',  'gmb_location_name' => '焼肉一番かるび 座光寺店　　', 'gmb_queries_direct' => '200', 'gmb_queries_indirect' => '232', 'gmb_queries_chain' => '99', 'gmb_actions_website' => '22', 'gmb_actions_phone' => '33', 'gmb_actions_driving_directions' => '22', ],
            ['location_report_id' => '11', 'location_id' => '2', 'aggregate_date' => '2020-08-08 00:00:00', 'gmb_account_id' => '002', 'gmb_location_id' => '002',  'gmb_location_name' => '焼肉一番かるび 白根店　　　', 'gmb_queries_direct' => '144', 'gmb_queries_indirect' => '333', 'gmb_queries_chain' => '33', 'gmb_actions_website' => '30', 'gmb_actions_phone' => '20', 'gmb_actions_driving_directions' => '50', ],
            ['location_report_id' => '12', 'location_id' => '3', 'aggregate_date' => '2020-08-10 00:00:00', 'gmb_account_id' => '002', 'gmb_location_id' => '003',  'gmb_location_name' => '焼肉一番かるび 北習志野店　', 'gmb_queries_direct' => '555', 'gmb_queries_indirect' => '333', 'gmb_queries_chain' => '111', 'gmb_actions_website' => '100', 'gmb_actions_phone' => '133', 'gmb_actions_driving_directions' => '100', ],
            ['location_report_id' => '13', 'location_id' => '4', 'aggregate_date' => '2019-03-12 00:00:00', 'gmb_account_id' => '003', 'gmb_location_id' => '004',  'gmb_location_name' => '丸源ラーメン つくば店　　　', 'gmb_queries_direct' => '200', 'gmb_queries_indirect' => '232', 'gmb_queries_chain' => '99', 'gmb_actions_website' => '22', 'gmb_actions_phone' => '33', 'gmb_actions_driving_directions' => '22', ],
            ['location_report_id' => '14', 'location_id' => '5', 'aggregate_date' => '2019-03-12 00:00:00', 'gmb_account_id' => '003', 'gmb_location_id' => '005',  'gmb_location_name' => '丸源ラーメン 伊丹店　　　　', 'gmb_queries_direct' => '144', 'gmb_queries_indirect' => '333', 'gmb_queries_chain' => '33', 'gmb_actions_website' => '30', 'gmb_actions_phone' => '20', 'gmb_actions_driving_directions' => '50', ],
            ['location_report_id' => '15', 'location_id' => '6', 'aggregate_date' => '2019-04-12 00:00:00', 'gmb_account_id' => '003', 'gmb_location_id' => '006',  'gmb_location_name' => '丸源ラーメン 一宮バイパス店', 'gmb_queries_direct' => '555', 'gmb_queries_indirect' => '333', 'gmb_queries_chain' => '111', 'gmb_actions_website' => '100', 'gmb_actions_phone' => '133', 'gmb_actions_driving_directions' => '100', ],
            ['location_report_id' => '16', 'location_id' => '4', 'aggregate_date' => '2019-04-13 00:00:00', 'gmb_account_id' => '003', 'gmb_location_id' => '004',  'gmb_location_name' => '丸源ラーメン つくば店　　　', 'gmb_queries_direct' => '200', 'gmb_queries_indirect' => '232', 'gmb_queries_chain' => '99', 'gmb_actions_website' => '22', 'gmb_actions_phone' => '33', 'gmb_actions_driving_directions' => '22', ],
            ['location_report_id' => '17', 'location_id' => '5', 'aggregate_date' => '2020-05-13 00:00:00', 'gmb_account_id' => '003', 'gmb_location_id' => '005',  'gmb_location_name' => '丸源ラーメン 伊丹店　　　　', 'gmb_queries_direct' => '144', 'gmb_queries_indirect' => '333', 'gmb_queries_chain' => '33', 'gmb_actions_website' => '30', 'gmb_actions_phone' => '20', 'gmb_actions_driving_directions' => '50', ],
            ['location_report_id' => '18', 'location_id' => '6', 'aggregate_date' => '2020-05-13 00:00:00', 'gmb_account_id' => '003', 'gmb_location_id' => '006',  'gmb_location_name' => '丸源ラーメン 一宮バイパス店', 'gmb_queries_direct' => '555', 'gmb_queries_indirect' => '333', 'gmb_queries_chain' => '111', 'gmb_actions_website' => '100', 'gmb_actions_phone' => '133', 'gmb_actions_driving_directions' => '100', ],
            ['location_report_id' => '19', 'location_id' => '4', 'aggregate_date' => '2020-06-14 00:00:00', 'gmb_account_id' => '003', 'gmb_location_id' => '004',  'gmb_location_name' => '丸源ラーメン つくば店　　　', 'gmb_queries_direct' => '222', 'gmb_queries_indirect' => '399', 'gmb_queries_chain' => '66', 'gmb_actions_website' => '50', 'gmb_actions_phone' => '20', 'gmb_actions_driving_directions' => '31', ],
            ['location_report_id' => '20', 'location_id' => '5', 'aggregate_date' => '2020-06-14 00:00:00', 'gmb_account_id' => '003', 'gmb_location_id' => '005',  'gmb_location_name' => '丸源ラーメン 伊丹店　　　　', 'gmb_queries_direct' => '111', 'gmb_queries_indirect' => '188', 'gmb_queries_chain' => '77', 'gmb_actions_website' => '28', 'gmb_actions_phone' => '40', 'gmb_actions_driving_directions' => '20', ],
            ['location_report_id' => '21', 'location_id' => '6', 'aggregate_date' => '2020-07-14 00:00:00', 'gmb_account_id' => '003', 'gmb_location_id' => '006',  'gmb_location_name' => '丸源ラーメン 一宮バイパス店', 'gmb_queries_direct' => '444', 'gmb_queries_indirect' => '322', 'gmb_queries_chain' => '100', 'gmb_actions_website' => '33', 'gmb_actions_phone' => '66', 'gmb_actions_driving_directions' => '0', ],
            ['location_report_id' => '22', 'location_id' => '4', 'aggregate_date' => '2020-07-15 00:00:00', 'gmb_account_id' => '003', 'gmb_location_id' => '004',  'gmb_location_name' => '丸源ラーメン つくば店　　　', 'gmb_queries_direct' => '222', 'gmb_queries_indirect' => '399', 'gmb_queries_chain' => '66', 'gmb_actions_website' => '50', 'gmb_actions_phone' => '20', 'gmb_actions_driving_directions' => '31', ],
            ['location_report_id' => '23', 'location_id' => '5', 'aggregate_date' => '2020-08-10 00:00:00', 'gmb_account_id' => '003', 'gmb_location_id' => '005',  'gmb_location_name' => '丸源ラーメン 伊丹店　　　　', 'gmb_queries_direct' => '111', 'gmb_queries_indirect' => '188', 'gmb_queries_chain' => '77', 'gmb_actions_website' => '28', 'gmb_actions_phone' => '40', 'gmb_actions_driving_directions' => '20', ],
            ['location_report_id' => '24', 'location_id' => '6', 'aggregate_date' => '2020-08-10 00:00:00', 'gmb_account_id' => '003', 'gmb_location_id' => '006',  'gmb_location_name' => '丸源ラーメン 一宮バイパス店', 'gmb_queries_direct' => '444', 'gmb_queries_indirect' => '322', 'gmb_queries_chain' => '100', 'gmb_actions_website' => '33', 'gmb_actions_phone' => '66', 'gmb_actions_driving_directions' => '0', ],
        ]);
    }
}
